"""Shared report design system — a light, print-friendly theme that every
Pulse report template (PDF via reportlab + HTML) inherits.

Two parallel surfaces, one look:

  * HTML  — `RPT_CSS` (one self-contained stylesheet) + `html_*` builders.
  * PDF   — `pdf_styles()`, `NumberedCanvas` (brand header + "Page X of Y"
            footer on every page), and `pdf_*` flowable builders.

Both use the same palette and severity colors so a printed PDF and the
in-browser HTML are visually identical. Templates keep their own content
and section order; they just compose these components.

Palette is a light/print adaptation of the dark dashboard tokens (see
.claude/skills/pulse-design.md) — white page, dark-gray body, color
reserved for severity and section accents.
"""
from __future__ import annotations

import html as _html
from typing import Any, List, Optional, Sequence, Tuple

from pulse import __version__ as PULSE_VERSION

# ---------------------------------------------------------------------------
# Palette (light / print)
# ---------------------------------------------------------------------------
C_TEXT   = "#1a1a1a"   # body
C_TITLE  = "#0f1420"   # headings
C_MUTED  = "#6b7280"   # secondary text, "None recorded"
C_FAINT  = "#9aa0aa"   # hints
C_BORDER = "#e2e5ea"   # hairlines, table grid
C_RULE   = "#cfd4dc"   # header/footer divider
C_TINT   = "#f6f8fa"   # zebra stripe, panel tint
C_ACCENT = "#2c5fd6"   # brand blue (darkened for paper)
C_WHITE  = "#ffffff"

# Severity — same hues as the dashboard, nudged for legibility on white.
SEV_FG = {
    "CRITICAL": "#c62828",  # red
    "HIGH":     "#e0700c",  # orange
    "MEDIUM":   "#c08a00",  # amber
    "LOW":      "#2563c9",  # blue
    "NONE":     "#6b7280",
    "INFO":     "#6b7280",
}
SEV_BG = {
    "CRITICAL": "#fbe9e9",
    "HIGH":     "#fdf0e2",
    "MEDIUM":   "#fbf3d9",
    "LOW":      "#e8f0fc",
    "NONE":     "#f1f3f5",
    "INFO":     "#f1f3f5",
}
STATUS_LABEL = {
    "new": "New", "acknowledged": "Acknowledged",
    "investigating": "Investigating", "resolved": "Resolved",
}

GITHUB = "github.com/barrytd/Pulse"
BRAND  = "PULSE"
BRAND_SUB = "Threat Detection"
FOOTER_LINE = "Generated by Pulse Threat Detection · " + GITHUB + " · v" + str(PULSE_VERSION)


def sev_key(sev: Any) -> str:
    s = str(sev or "NONE").upper()
    return s if s in SEV_FG else "NONE"


def esc(s: Any) -> str:
    return _html.escape("" if s is None else str(s))


# ===========================================================================
# HTML
# ===========================================================================

RPT_CSS = """
@page { size: Letter; margin: 50px 50px 64px; }
* { box-sizing: border-box; }
html, body { margin: 0; padding: 0; }
body {
  font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
  font-size: 10.5pt; line-height: 1.5; color: %(text)s; background: %(white)s;
  -webkit-print-color-adjust: exact; print-color-adjust: exact;
}
.rpt-page { max-width: 760px; margin: 0 auto; padding: 28px 36px 40px; }
.rpt-mono { font-family: 'SFMono-Regular', Menlo, Consolas, 'Liberation Mono', monospace; }
.rpt-none { color: %(muted)s; font-style: italic; }

/* Running header / footer (repeat on every printed page) */
.rpt-runhead, .rpt-runfoot { position: fixed; left: 0; right: 0; padding: 0 36px; }
.rpt-runhead { top: 0; }
.rpt-runfoot { bottom: 0; }
@media screen {
  .rpt-runhead, .rpt-runfoot { position: static; padding: 0; }
  .rpt-page { padding-top: 12px; }
}
.rpt-brandbar {
  display: flex; align-items: flex-end; justify-content: space-between;
  border-bottom: 1.5px solid %(rule)s; padding: 10px 0 8px; margin-bottom: 4px;
}
.rpt-brand { display: flex; align-items: baseline; gap: 8px; }
.rpt-brand-mark { font-weight: 800; font-size: 13px; letter-spacing: 2px; color: %(accent)s; }
.rpt-brand-sub { font-size: 9px; letter-spacing: 1px; text-transform: uppercase; color: %(muted)s; }
.rpt-eyebrow-r { font-size: 9px; letter-spacing: 1.4px; text-transform: uppercase; color: %(muted)s; font-weight: 700; }
.rpt-footbar {
  display: flex; align-items: center; justify-content: space-between;
  border-top: 1px solid %(rule)s; padding: 8px 0; margin-top: 4px;
  font-size: 8px; color: %(muted)s; letter-spacing: 0.2px;
}

/* Title block */
.rpt-eyebrow { font-size: 9.5px; letter-spacing: 2px; text-transform: uppercase; color: %(accent)s; font-weight: 700; }
.rpt-title { font-size: 23px; font-weight: 800; color: %(title)s; margin: 4px 0 14px; letter-spacing: -0.2px; }
.rpt-meta-grid {
  display: grid; grid-template-columns: max-content 1fr; gap: 4px 16px;
  font-size: 10px; margin: 0 0 16px;
}
.rpt-meta-grid .k { color: %(muted)s; text-transform: uppercase; letter-spacing: 0.5px; font-size: 8.5px; font-weight: 600; padding-top: 1px; }
.rpt-meta-grid .v { color: %(text)s; }

/* Classification banner */
.rpt-banner {
  border-radius: 5px; padding: 9px 14px; margin: 0 0 18px;
  color: #fff; font-weight: 700; font-size: 11px; letter-spacing: 0.4px;
  display: flex; align-items: center; gap: 8px;
}
.rpt-banner small { font-weight: 500; opacity: 0.92; letter-spacing: 0; text-transform: none; }

/* Section header — uppercase label + accent bar */
.rpt-section { margin: 22px 0 10px; display: flex; align-items: center; gap: 8px; }
.rpt-section-bar { width: 3px; height: 13px; border-radius: 2px; background: %(accent)s; }
.rpt-section-label { font-size: 11px; font-weight: 700; letter-spacing: 1px; text-transform: uppercase; color: %(title)s; }

/* Severity pill */
.rpt-pill { display: inline-block; padding: 1.5px 8px; border-radius: 10px; font-size: 8.5px; font-weight: 700; letter-spacing: 0.4px; }
.rpt-badge { display: inline-block; padding: 1.5px 8px; border-radius: 10px; font-size: 8.5px; font-weight: 600; border: 1px solid %(border)s; color: %(muted)s; background: %(white)s; }

/* Callout */
.rpt-callout { border: 1px solid %(border)s; border-left: 3px solid %(accent)s; background: %(tint)s; border-radius: 5px; padding: 12px 14px; margin: 0 0 8px; font-size: 10px; }
.rpt-callout-verdict { font-size: 11.5px; color: %(title)s; font-weight: 600; line-height: 1.45; }
.rpt-chips { margin-top: 9px; }
.rpt-chips .rpt-pill { margin-right: 6px; }

/* Asset rows */
.rpt-asset { display: grid; grid-template-columns: 120px 1fr; gap: 4px 12px; font-size: 10px; margin-bottom: 4px; }
.rpt-asset .k { color: %(muted)s; text-transform: uppercase; letter-spacing: 0.5px; font-size: 8.5px; font-weight: 600; padding-top: 1px; }

/* Tables */
.rpt-table { width: 100%%; border-collapse: collapse; font-size: 9.5px; margin: 2px 0 6px; }
.rpt-table th { text-align: left; background: %(tint)s; color: %(muted)s; text-transform: uppercase; letter-spacing: 0.4px; font-size: 8px; font-weight: 700; padding: 6px 9px; border-bottom: 1px solid %(border)s; }
.rpt-table td { padding: 6px 9px; border-bottom: 1px solid %(border)s; color: %(text)s; vertical-align: top; }
.rpt-table tbody tr:nth-child(even) td { background: #fafbfc; }
.rpt-table td.num, .rpt-table th.num { text-align: right; }

/* Finding cards */
.rpt-card { border: 1px solid %(border)s; border-left-width: 4px; border-radius: 6px; padding: 12px 14px; margin: 0 0 12px; page-break-inside: avoid; }
.rpt-card-head { display: flex; align-items: center; flex-wrap: wrap; gap: 7px; margin-bottom: 5px; }
.rpt-card-num { font-weight: 800; color: %(muted)s; font-size: 10px; }
.rpt-card-rule { font-weight: 700; color: %(title)s; font-size: 12px; }
.rpt-card-meta { font-size: 9px; color: %(muted)s; margin: 4px 0 6px; }
.rpt-card-meta b { color: %(text)s; font-weight: 600; }
.rpt-card-desc { font-size: 10px; color: %(text)s; line-height: 1.5; }
.rpt-card-sha { font-size: 8px; color: %(faint)s; margin-top: 7px; }

/* Chain of custody */
.rpt-coc { border: 1px solid %(border)s; border-radius: 6px; padding: 14px 16px; }
.rpt-coc-digest { background: %(tint)s; border: 1px solid %(border)s; border-radius: 5px; padding: 10px 12px; margin: 10px 0; font-size: 9.5px; word-break: break-all; }
.rpt-coc-digest .lbl { display: block; font-size: 8px; text-transform: uppercase; letter-spacing: 0.6px; color: %(muted)s; font-weight: 700; margin-bottom: 3px; }
""" % {
    "text": C_TEXT, "title": C_TITLE, "muted": C_MUTED, "faint": C_FAINT,
    "border": C_BORDER, "rule": C_RULE, "tint": C_TINT, "accent": C_ACCENT,
    "white": C_WHITE,
}


def html_document(report_type: str, doc_title: str, body_html: str) -> str:
    """Wrap section HTML in a full, self-contained light-theme document with
    the brand running-header + footer."""
    head = (
        '<div class="rpt-runhead"><div class="rpt-brandbar">'
        '<div class="rpt-brand"><span class="rpt-brand-mark">' + esc(BRAND) + '</span>'
        '<span class="rpt-brand-sub">' + esc(BRAND_SUB) + '</span></div>'
        '<div class="rpt-eyebrow-r">' + esc(report_type) + '</div></div></div>'
    )
    foot = (
        '<div class="rpt-runfoot"><div class="rpt-footbar">'
        '<span>' + esc(FOOTER_LINE) + '</span>'
        '<span>Confidential</span></div></div>'
    )
    return (
        '<!doctype html><html lang="en"><head><meta charset="utf-8">'
        '<meta name="viewport" content="width=device-width, initial-scale=1">'
        '<title>' + esc(doc_title) + '</title><style>' + RPT_CSS + '</style></head>'
        '<body>' + head + '<div class="rpt-page">' + body_html + '</div>' + foot +
        '</body></html>'
    )


def html_eyebrow_title(eyebrow: str, title: str) -> str:
    return ('<div class="rpt-eyebrow">' + esc(eyebrow) + '</div>'
            '<div class="rpt-title">' + esc(title) + '</div>')


def html_metadata_grid(pairs: Sequence[Tuple[str, str]]) -> str:
    cells = "".join(
        '<div class="k">' + esc(k) + '</div><div class="v">' + (v or html_none()) + '</div>'
        for k, v in pairs
    )
    return '<div class="rpt-meta-grid">' + cells + '</div>'


def html_classification_banner(sev: str, label: Optional[str] = None) -> str:
    k = sev_key(sev)
    txt = label or (("Critical incident" if k == "CRITICAL"
                     else "High-severity incident" if k == "HIGH"
                     else "Moderate findings" if k == "MEDIUM"
                     else "Low-severity findings" if k == "LOW"
                     else "No active findings"))
    return ('<div class="rpt-banner" style="background:' + SEV_FG[k] + ';">'
            'CLASSIFICATION<small>' + esc(txt) + '</small></div>')


def html_section(label: str, inner: str, accent_sev: Optional[str] = None) -> str:
    bar = ' style="background:' + SEV_FG[sev_key(accent_sev)] + ';"' if accent_sev else ""
    return ('<div class="rpt-section"><span class="rpt-section-bar"' + bar + '></span>'
            '<span class="rpt-section-label">' + esc(label) + '</span></div>' + inner)


def html_pill(sev: str) -> str:
    k = sev_key(sev)
    return ('<span class="rpt-pill" style="color:' + SEV_FG[k] + ';background:' + SEV_BG[k] + ';">'
            + esc(k) + '</span>')


def html_status_badge(status: str) -> str:
    return '<span class="rpt-badge">' + esc(STATUS_LABEL.get((status or "new").lower(), "New")) + '</span>'


def html_none() -> str:
    return '<span class="rpt-none">None recorded</span>'


def html_table(headers: Sequence[str], rows: Sequence[Sequence[str]],
               num_cols: Sequence[int] = ()) -> str:
    nset = set(num_cols)
    thead = "".join(
        '<th' + (' class="num"' if i in nset else "") + '>' + esc(h) + '</th>'
        for i, h in enumerate(headers))
    body = ""
    for r in rows:
        tds = "".join(
            '<td' + (' class="num"' if i in nset else "") + '>' + (c if c else "") + '</td>'
            for i, c in enumerate(r))
        body += '<tr>' + tds + '</tr>'
    return ('<table class="rpt-table"><thead><tr>' + thead + '</tr></thead>'
            '<tbody>' + body + '</tbody></table>')


def html_callout(inner: str, accent_sev: Optional[str] = None) -> str:
    style = ' style="border-left-color:' + SEV_FG[sev_key(accent_sev)] + ';"' if accent_sev else ""
    return '<div class="rpt-callout"' + style + '>' + inner + '</div>'


# ===========================================================================
# PDF (reportlab)
# ===========================================================================

def _rl():
    """Import reportlab lazily so HTML/JSON/CSV paths don't pay for it."""
    from reportlab.lib import colors
    from reportlab.lib.enums import TA_LEFT, TA_RIGHT, TA_CENTER
    from reportlab.lib.pagesizes import LETTER
    from reportlab.lib.styles import ParagraphStyle
    from reportlab.lib.units import inch
    from reportlab.pdfgen import canvas as _canvas
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Flowable,
        KeepTogether,
    )
    return dict(colors=colors, TA_LEFT=TA_LEFT, TA_RIGHT=TA_RIGHT, TA_CENTER=TA_CENTER,
                LETTER=LETTER, ParagraphStyle=ParagraphStyle, inch=inch, canvas=_canvas,
                SimpleDocTemplate=SimpleDocTemplate, Paragraph=Paragraph, Spacer=Spacer,
                Table=Table, TableStyle=TableStyle, Flowable=Flowable, KeepTogether=KeepTogether)


MARGIN = 50          # ~50px page margins (points)
PAGE_W = 612         # Letter width in points
CONTENT_W = PAGE_W - 2 * MARGIN


def make_numbered_canvas(report_type: str):
    """Return a canvasmaker that stamps the brand header + 'Page X of Y'
    footer on every page (two-pass so the total is known)."""
    rl = _rl()
    Canvas = rl["canvas"].Canvas
    colors = rl["colors"]

    class NumberedCanvas(Canvas):
        def __init__(self, *a, **kw):
            Canvas.__init__(self, *a, **kw)
            self._saved = []

        def showPage(self):
            self._saved.append(dict(self.__dict__))
            self._startPage()

        def save(self):
            total = len(self._saved)
            for state in self._saved:
                self.__dict__.update(state)
                self._draw_furniture(total)
                Canvas.showPage(self)
            Canvas.save(self)

        def _draw_furniture(self, total):
            w, h = self._pagesize
            # ---- header ----
            self.setFillColor(colors.HexColor(C_ACCENT))
            self.setFont("Helvetica-Bold", 11)
            self.drawString(MARGIN, h - 38, BRAND)
            bw = self.stringWidth(BRAND, "Helvetica-Bold", 11)
            self.setFillColor(colors.HexColor(C_MUTED))
            self.setFont("Helvetica", 7)
            self.drawString(MARGIN + bw + 6, h - 38, BRAND_SUB.upper())
            self.drawRightString(w - MARGIN, h - 38, report_type.upper())
            self.setStrokeColor(colors.HexColor(C_RULE))
            self.setLineWidth(1)
            self.line(MARGIN, h - 46, w - MARGIN, h - 46)
            # ---- footer ----
            self.line(MARGIN, 40, w - MARGIN, 40)
            self.setFillColor(colors.HexColor(C_MUTED))
            self.setFont("Helvetica", 7)
            self.drawString(MARGIN, 30, "Page %d of %d" % (self._pageNumber, total))
            self.drawRightString(w - MARGIN, 30, FOOTER_LINE)

    return NumberedCanvas


def pdf_styles():
    rl = _rl()
    PS = rl["ParagraphStyle"]
    C = rl["colors"].HexColor
    return {
        "eyebrow": PS("rpt_eyebrow", fontName="Helvetica-Bold", fontSize=8, leading=11,
                      textColor=C(C_ACCENT), spaceAfter=2),
        "title": PS("rpt_title", fontName="Helvetica-Bold", fontSize=20, leading=24,
                    textColor=C(C_TITLE), spaceAfter=2),
        "body": PS("rpt_body", fontName="Helvetica", fontSize=9.5, leading=14, textColor=C(C_TEXT)),
        "muted": PS("rpt_muted", fontName="Helvetica", fontSize=9, leading=13, textColor=C(C_MUTED)),
        "mono": PS("rpt_mono", fontName="Courier", fontSize=8, leading=11, textColor=C(C_TEXT)),
        "section": PS("rpt_section", fontName="Helvetica-Bold", fontSize=10.5, leading=14,
                      textColor=C(C_TITLE)),
        "verdict": PS("rpt_verdict", fontName="Helvetica-Bold", fontSize=11, leading=16,
                      textColor=C(C_TITLE)),
        "cardrule": PS("rpt_cardrule", fontName="Helvetica-Bold", fontSize=11, leading=14,
                       textColor=C(C_TITLE)),
        "th": PS("rpt_th", fontName="Helvetica-Bold", fontSize=7.5, leading=10, textColor=C(C_MUTED)),
        "td": PS("rpt_td", fontName="Helvetica", fontSize=8.5, leading=12, textColor=C(C_TEXT)),
        "tdmono": PS("rpt_tdmono", fontName="Courier", fontSize=7.5, leading=11, textColor=C(C_TEXT)),
    }


def new_doc(buf, title: str, report_type: str):
    """A configured SimpleDocTemplate + its canvasmaker. Build with
    ``doc.build(story, canvasmaker=canvasmaker)``."""
    rl = _rl()
    doc = rl["SimpleDocTemplate"](
        buf, pagesize=rl["LETTER"],
        leftMargin=MARGIN, rightMargin=MARGIN,
        topMargin=58, bottomMargin=52, title=title,
    )
    return doc, make_numbered_canvas(report_type)


def pdf_section(label: str, styles, accent_sev: Optional[str] = None):
    """Section header: a small colored accent bar + uppercase label."""
    rl = _rl()
    C = rl["colors"].HexColor
    bar = C(SEV_FG[sev_key(accent_sev)]) if accent_sev else C(C_ACCENT)
    cell = rl["Paragraph"](
        '<font color="%s"><b>%s</b></font>' % (C_TITLE, esc(label).upper()), styles["section"])
    t = rl["Table"]([["", cell]], colWidths=[4, CONTENT_W - 4])
    t.setStyle(rl["TableStyle"]([
        ("BACKGROUND", (0, 0), (0, 0), bar),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (0, 0), 0), ("RIGHTPADDING", (0, 0), (0, 0), 0),
        ("LEFTPADDING", (1, 0), (1, 0), 8),
        ("TOPPADDING", (0, 0), (-1, -1), 2), ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
    ]))
    return t


def pdf_pill_para(sev: str, styles):
    """A severity pill as a one-cell Table flowable (inline use is awkward in
    reportlab, so pills live in their own cell)."""
    rl = _rl()
    C = rl["colors"].HexColor
    k = sev_key(sev)
    p = rl["Paragraph"]('<font color="%s"><b>%s</b></font>' % (SEV_FG[k], esc(k)),
                        rl["ParagraphStyle"]("pill", fontName="Helvetica-Bold", fontSize=7.5,
                                             leading=10, alignment=rl["TA_CENTER"]))
    w = 8 + 5.6 * len(k)
    t = rl["Table"]([[p]], colWidths=[w])
    t.setStyle(rl["TableStyle"]([
        ("BACKGROUND", (0, 0), (-1, -1), C(SEV_BG[k])),
        ("TOPPADDING", (0, 0), (-1, -1), 2), ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
        ("LEFTPADDING", (0, 0), (-1, -1), 5), ("RIGHTPADDING", (0, 0), (-1, -1), 5),
        ("ROUNDEDCORNERS", [5, 5, 5, 5]),
    ]))
    t.hAlign = "LEFT"
    return t


def pdf_banner(sev: str, label: str, styles):
    rl = _rl()
    C = rl["colors"].HexColor
    k = sev_key(sev)
    p = rl["Paragraph"](
        '<font color="#ffffff"><b>CLASSIFICATION</b>&nbsp;&nbsp;%s</font>' % esc(label),
        rl["ParagraphStyle"]("ban", fontName="Helvetica-Bold", fontSize=10, leading=14,
                             textColor=rl["colors"].white))
    t = rl["Table"]([[p]], colWidths=[CONTENT_W])
    t.setStyle(rl["TableStyle"]([
        ("BACKGROUND", (0, 0), (-1, -1), C(SEV_FG[k])),
        ("TOPPADDING", (0, 0), (-1, -1), 7), ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
        ("LEFTPADDING", (0, 0), (-1, -1), 12), ("RIGHTPADDING", (0, 0), (-1, -1), 12),
        ("ROUNDEDCORNERS", [4, 4, 4, 4]),
    ]))
    return t


def pdf_metadata_grid(pairs: Sequence[Tuple[str, str]], styles):
    rl = _rl()
    data = []
    for k, v in pairs:
        data.append([
            rl["Paragraph"](esc(k).upper(), styles["th"]),
            rl["Paragraph"](v if v else '<font color="%s"><i>None recorded</i></font>' % C_MUTED, styles["td"]),
        ])
    t = rl["Table"](data, colWidths=[110, CONTENT_W - 110])
    t.setStyle(rl["TableStyle"]([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING", (0, 0), (-1, -1), 1.5), ("BOTTOMPADDING", (0, 0), (-1, -1), 1.5),
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
    ]))
    return t


def pdf_callout(flowables: list, styles, accent_sev: Optional[str] = None):
    rl = _rl()
    C = rl["colors"].HexColor
    accent = C(SEV_FG[sev_key(accent_sev)]) if accent_sev else C(C_ACCENT)
    t = rl["Table"]([[flowables]], colWidths=[CONTENT_W])
    t.setStyle(rl["TableStyle"]([
        ("BACKGROUND", (0, 0), (-1, -1), C(C_TINT)),
        ("BOX", (0, 0), (-1, -1), 0.6, C(C_BORDER)),
        ("LINEBEFORE", (0, 0), (0, -1), 2.5, accent),
        ("TOPPADDING", (0, 0), (-1, -1), 10), ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
        ("LEFTPADDING", (0, 0), (-1, -1), 12), ("RIGHTPADDING", (0, 0), (-1, -1), 12),
    ]))
    return t


def pdf_table(headers: Sequence[str], rows: Sequence[Sequence[Any]], col_widths,
              styles, *, mono_cols=()):
    """A zebra-striped table with a shaded header. Cells may be strings
    (wrapped as Paragraphs) or pre-built flowables (e.g. a pill)."""
    rl = _rl()
    C = rl["colors"].HexColor
    mono = set(mono_cols)

    def cell(i, v):
        if hasattr(v, "wrapOn") or isinstance(v, list):
            return v
        return rl["Paragraph"](esc(v), styles["tdmono"] if i in mono else styles["td"])

    data = [[rl["Paragraph"](esc(h).upper(), styles["th"]) for h in headers]]
    for r in rows:
        data.append([cell(i, v) for i, v in enumerate(r)])
    t = rl["Table"](data, colWidths=col_widths, repeatRows=1)
    style = [
        ("BACKGROUND", (0, 0), (-1, 0), C(C_TINT)),
        ("LINEBELOW", (0, 0), (-1, 0), 0.7, C(C_BORDER)),
        ("LINEBELOW", (0, 1), (-1, -1), 0.4, C(C_BORDER)),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING", (0, 0), (-1, -1), 5), ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 9), ("RIGHTPADDING", (0, 0), (-1, -1), 9),
    ]
    for ridx in range(2, len(data), 2):
        style.append(("BACKGROUND", (0, ridx), (-1, ridx), C("#fafbfc")))
    t.setStyle(rl["TableStyle"](style))
    return t


def pdf_finding_card(num: int, f: dict, styles):
    """A finding card with a severity-colored left border."""
    rl = _rl()
    C = rl["colors"].HexColor
    k = sev_key(f.get("severity"))

    head_bits = ['<font color="%s"><b>#%d</b></font>' % (C_MUTED, num),
                 '<font color="%s"><b>%s</b></font>' % (C_TITLE, esc(f.get("rule") or "Unknown"))]
    head = rl["Paragraph"]("&nbsp;&nbsp;".join(head_bits), styles["cardrule"])

    tags = [pdf_pill_para(k, styles)]
    sub = []
    if f.get("ref_id"):
        sub.append('<font face="Courier" color="%s">%s</font>' % (C_MUTED, esc(f["ref_id"])))
    if f.get("mitre"):
        sub.append('<font color="%s">%s</font>' % (C_ACCENT, esc(f["mitre"])))
    sub.append('<font color="%s">%s</font>' % (C_MUTED, esc(STATUS_LABEL.get((f.get("workflow_status") or "new"), "New"))))
    sub_p = rl["Paragraph"]("&nbsp;·&nbsp;".join(sub), styles["muted"])

    meta_bits = []
    meta_bits.append("<b>When</b> " + esc(f.get("timestamp") or "—"))
    meta_bits.append("<b>Host</b> " + (esc(f["hostname"]) if f.get("hostname") else '<i><font color="%s">None</font></i>' % C_MUTED))
    meta_bits.append("<b>Account</b> " + (esc(f["account"]) if f.get("account") else '<i><font color="%s">None</font></i>' % C_MUTED))
    meta_bits.append("<b>Source IP</b> " + (esc(f["source_ip"]) if f.get("source_ip") else '<i><font color="%s">None</font></i>' % C_MUTED))
    meta = rl["Paragraph"]('<font color="%s" size="8">%s</font>' % (C_MUTED, " &nbsp;·&nbsp; ".join(meta_bits)), styles["muted"])

    desc = rl["Paragraph"](esc(f.get("description") or "No description recorded."), styles["body"])
    sha = rl["Paragraph"]('<font color="%s" face="Courier" size="7">Evidence SHA-256: %s</font>'
                          % (C_FAINT, esc(f.get("sha256") or "—")), styles["mono"])

    inner = rl["Table"]([[head], [tags[0]], [sub_p], [rl["Spacer"](1, 3)], [meta], [desc], [sha]],
                        colWidths=[CONTENT_W - 16])
    inner.setStyle(rl["TableStyle"]([
        ("LEFTPADDING", (0, 0), (-1, -1), 0), ("RIGHTPADDING", (0, 0), (-1, -1), 0),
        ("TOPPADDING", (0, 0), (-1, -1), 1.5), ("BOTTOMPADDING", (0, 0), (-1, -1), 1.5),
    ]))

    card = rl["Table"]([[inner]], colWidths=[CONTENT_W])
    card.setStyle(rl["TableStyle"]([
        ("BOX", (0, 0), (-1, -1), 0.6, C(C_BORDER)),
        ("LINEBEFORE", (0, 0), (0, -1), 4, C(SEV_FG[k])),
        ("TOPPADDING", (0, 0), (-1, -1), 10), ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
        ("LEFTPADDING", (0, 0), (-1, -1), 12), ("RIGHTPADDING", (0, 0), (-1, -1), 12),
    ]))
    return rl["KeepTogether"]([card])


def pdf_spacer(h=8):
    return _rl()["Spacer"](1, h)
